### ISSUE TITLE
Sadece Takip Bilgisi Çekilmesi

### ISSUE THREAD

**Issue by holymong** [canavci2016/yurt-ici-kargo#2]
Merhaba,

Bir entegrasyon kullanıyoruz, WooCommerce Trendyol Hepsiburada vs. bütün siparişler bu entegrasyondan yönetiliyor. Programın kendi entegrasyonu mevcut Yurtiçi kargo ile sipariş bilgilerini iletip kargo kodu çıkartabiliyoruz sıkıntı yok. 

Fakat WooCommerce'de kargo fiziksel olarak kargo firmasına gittikten sonra takip kodunu API'dan çekip müşteriye göndermemiz gerekiyor. Müşteriye manuel olarak sipariş kargo kodunu yazıp gönderecek bir eklentimiz mevcut fakat. API ve cronjob ile bunu otomasyona bağlayabilir miyiz. Zamanınız varsa bir yönlendirme yapabilir misiniz? Gönderi oluşturma için örnek vermişsiniz ama takip kodu çekmek için bir örnek yok çözemedim bende.

**Comment by holymong** [comment]
Ek olarak söylemeyi unutmuşum WooCommerce databaseinde tutulan sipariş numarası kargo fişi çıkarılırken Sevk İrsaliye No ($waybillNo) alanına yazılıyor. Dolayısıyla Wordpress içerisinden $waybillNo iletip kargo kodu ile geri dönen bir sistem lazım.

**Comment by canavci2016** [comment]
> Merhaba,
> 
> Bir entegrasyon kullanıyoruz, WooCommerce Trendyol Hepsiburada vs. bütün siparişler bu entegrasyondan yönetiliyor. Programın kendi entegrasyonu mevcut Yurtiçi kargo ile sipariş bilgilerini iletip kargo kodu çıkartabiliyoruz sıkıntı yok.
> 
> Fakat WooCommerce'de kargo fiziksel olarak kargo firmasına gittikten sonra takip kodunu API'dan çekip müşteriye göndermemiz gerekiyor. Müşteriye manuel olarak sipariş kargo kodunu yazıp gönderecek bir eklentimiz mevcut fakat. API ve cronjob ile bunu otomasyona bağlayabilir miyiz. Zamanınız varsa bir yönlendirme yapabilir misiniz? Gönderi oluşturma için örnek vermişsiniz ama takip kodu çekmek için bir örnek yok çözemedim bende.

Merhaba,  Biz panelden kargo firmasının api adresini çağırdıktan sonra bize bir kod dönmekte idi. ardından bu kodu gelen kargocuya verdiğimizde. kargocu bunu sistemde onaylıyordu. ve onayın ardından artık bu kod ile bilgileri çekebilmekteydik. Burda önemli olan gelen kargocu bu kodu elindeki cihazla onayladıktan sonra kargonun durumu öğrenilebiliyor.
